CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_cinema` AS select `a1`.`dtstart` AS `dtstart`,`a1`.`dtend` AS `dtend`,`a1`.`id` AS `id_cn_filme_post`,`a2`.`id` AS `id_cn_filme`,`a3`.`ID` AS `id_wp_post`,`a3`.`post_title` AS `post_title`,(select `wp_postmeta`.`meta_value` AS `state` from `wp_postmeta` where ((`wp_postmeta`.`post_id` = `a3`.`ID`) and (`wp_postmeta`.`meta_key` = 'vcard_region'))) AS `state`,(select `wp_postmeta`.`meta_value` AS `state` from `wp_postmeta` where ((`wp_postmeta`.`post_id` = `a3`.`ID`) and (`wp_postmeta`.`meta_key` = 'vcard_locality'))) AS `city`,(select `wp_postmeta`.`meta_value` AS `state` from `wp_postmeta` where ((`wp_postmeta`.`post_id` = `a3`.`ID`) and (`wp_postmeta`.`meta_key` = 'vcard_address'))) AS `address`,`a3`.`post_content` AS `post_content`,`a1`.`outras_informacoes` AS `outras_informacoes`,`a1`.`salas_horarios` AS `salas_horarios`,`a2`.`titulo` AS `titulo`,`a2`.`titulo_original` AS `titulo_original`,`a2`.`ano_producao` AS `ano_producao`,`a2`.`duracao` AS `duracao`,`a2`.`pais_origem` AS `pais_origem`,`a2`.`diretor` AS `diretor`,`a2`.`elenco` AS `elenco`,`a2`.`sinopse` AS `sinopse`,`a2`.`imagem_full` AS `imagem_full` from ((`wp_cn_filme_post` `a1` left join `wp_cn_filme` `a2` on((`a1`.`id_wp_cn_filme` = `a2`.`id`))) left join `wp_posts` `a3` on((`a3`.`ID` = `a1`.`id_wp_posts`)));

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_cultura_ids` AS select `wp_term_relationships`.`object_id` AS `object_id` from `wp_term_relationships` where `wp_term_relationships`.`term_taxonomy_id` in (select `wp_term_taxonomy`.`term_taxonomy_id` from `wp_term_taxonomy` where (`wp_term_taxonomy`.`term_id` in (select `wp_terms`.`term_id` from `wp_terms` where ((`wp_terms`.`name` like '%Cursos%') or (`wp_terms`.`name` like '%Exposição%') or (`wp_terms`.`name` like '%Inscrições%'))) and (`wp_term_taxonomy`.`taxonomy` = 'segmento'))) group by `wp_term_relationships`.`object_id` order by `wp_term_relationships`.`object_id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_destaque_ids` AS select `wp_term_relationships`.`object_id` AS `object_id` from `wp_term_relationships` where `wp_term_relationships`.`term_taxonomy_id` in (select `wp_term_taxonomy`.`term_taxonomy_id` from `wp_term_taxonomy` where (`wp_term_taxonomy`.`term_id` in (select `wp_terms`.`term_id` from `wp_terms` where (`wp_terms`.`name` like '%Atendimento%')) and (`wp_term_taxonomy`.`taxonomy` = 'segmento'))) group by `wp_term_relationships`.`object_id` order by `wp_term_relationships`.`object_id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_eventos_ids` AS select `wp_term_relationships`.`object_id` AS `object_id` from `wp_term_relationships` where `wp_term_relationships`.`term_taxonomy_id` in (select `wp_term_taxonomy`.`term_taxonomy_id` from `wp_term_taxonomy` where (`wp_term_taxonomy`.`term_id` in (select `wp_terms`.`term_id` from `wp_terms` where ((`wp_terms`.`name` like '%Palestra%') or (`wp_terms`.`name` like '%Workshop%') or (`wp_terms`.`name` like '%Inscrições%') or (`wp_terms`.`name` like '%Evento%'))) and (`wp_term_taxonomy`.`taxonomy` = 'segmento'))) group by `wp_term_relationships`.`object_id` order by `wp_term_relationships`.`object_id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_events` AS select `a`.`ID` AS `event_id`,`a`.`post_title` AS `event_tit`,`a`.`post_content` AS `event_info`,(select `wp_postmeta`.`meta_value` AS `state` from `wp_postmeta` where ((`wp_postmeta`.`post_id` = `a`.`ID`) and (`wp_postmeta`.`meta_key` = 'vcard_address'))) AS `event_endereco`,(select `wp_postmeta`.`meta_value` AS `state` from `wp_postmeta` where ((`wp_postmeta`.`post_id` = `a`.`ID`) and (`wp_postmeta`.`meta_key` = 'vcard_tel'))) AS `event_phone`,(select `wp_postmeta`.`meta_value` AS `state` from `wp_postmeta` where ((`wp_postmeta`.`post_id` = `a`.`ID`) and (`wp_postmeta`.`meta_key` = 'vcard_locality'))) AS `event_city`,(select `wp_postmeta`.`meta_value` AS `state` from `wp_postmeta` where ((`wp_postmeta`.`post_id` = `a`.`ID`) and (`wp_postmeta`.`meta_key` = 'vevent_location'))) AS `event_id_place` from `wp_posts` `a` where (`a`.`post_type` = 'evento');

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_lazer_ids` AS select `wp_term_relationships`.`object_id` AS `object_id` from `wp_term_relationships` where `wp_term_relationships`.`term_taxonomy_id` in (select `wp_term_taxonomy`.`term_taxonomy_id` from `wp_term_taxonomy` where (`wp_term_taxonomy`.`term_id` in (select `wp_terms`.`term_id` from `wp_terms` where ((`wp_terms`.`name` like '%Festas e Baladas%') or (`wp_terms`.`name` like '%Happy Our%') or (`wp_terms`.`name` like '%Shows%') or (`wp_terms`.`name` like '%Bares e Pubs%'))) and (`wp_term_taxonomy`.`taxonomy` = 'segmento'))) group by `wp_term_relationships`.`object_id` order by `wp_term_relationships`.`object_id`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_places` AS select `a`.`ID` AS `ID`,`a`.`post_title` AS `tit`,`a`.`post_content` AS `info`,(select `wp_postmeta`.`meta_value` AS `state` from `wp_postmeta` where ((`wp_postmeta`.`post_id` = `a`.`ID`) and (`wp_postmeta`.`meta_key` = 'vcard_address'))) AS `endereco`,(select `wp_postmeta`.`meta_value` AS `state` from `wp_postmeta` where ((`wp_postmeta`.`post_id` = `a`.`ID`) and (`wp_postmeta`.`meta_key` = 'vcard_tel'))) AS `telefone`,(select `wp_postmeta`.`meta_value` AS `state` from `wp_postmeta` where ((`wp_postmeta`.`post_id` = `a`.`ID`) and (`wp_postmeta`.`meta_key` = 'vcard_locality'))) AS `cidade`,(select `wp_postmeta`.`meta_value` AS `state` from `wp_postmeta` where ((`wp_postmeta`.`post_id` = `a`.`ID`) and (`wp_postmeta`.`meta_key` = 'vcard_email'))) AS `email` from `wp_posts` `a`;
